### ISSUE TITLE
board information missing on OAK-FFC 

### ISSUE THREAD

**Issue by oto313** [luxonis/Factory-calibration-DepthAI#9]
I am trying to get board information from OAK-FFC with following code: 
```
auto dev = std::make_unique<dai::Device>();
auto eeprom = dev->readCalibration().getEepromData();
auto boardName = eeprom.boardName;
auto boardRev= eeprom.boardRev;
```
Actual behavior:
boardName and boardRev are empty strings on OAK-FFC
on OAK-D it correctly returns OAK-D and R1M0E1

Expected behavior:
For OAK-FFC it should return correct boardName and boardRev and possibly other info.

Reason:
I need this info because you have introduces breaking change on OAK-FFC-3P (Different pinout on camera connector). And I need to give warning to user of our system that some cameras cannot be connected to this board.

Erik from your company pointed out that the OAK-FFC does not have camera so it is not needed to calibrate it. So nothing is flashed into eeprom. Maybe you can start flashing eeprom also on OAK-FFC.

Thanks

**Comment by daxoft** [comment]
@oto313 you can use the script inside the zip below, you'll just have to run it and wait a few minutes.
Please be careful with this, **only use the script for the [OAK-FFC-4P](https://shop.luxonis.com/products/oak-ffc-4p) device**, make sure **only one OAK-FFC-4P is connected to the PC**, and **do not disconnect the device while the script is running**.
[write_ffc_4p.zip](https://github.com/luxonis/Factory-calibration-DepthAI/files/8921815/write_ffc_4p.zip)

**Comment by oto313** [comment]
Ok thanks for information. But I have OAK-FFC-3P and OAK-FFC-3P-OG. I have all revisions as in this picture https://github.com/luxonis/depthai-hardware/blob/master/DM1090FFC_DepthAI_USB3/Images/Flowchart_FFC.png

**Comment by daxoft** [comment]
ah, ok, let me check

**Comment by oto313** [comment]
Hi @daxoft any progress?

**Comment by daxoft** [comment]
[flash_FFC_3P.zip](https://github.com/luxonis/Factory-calibration-DepthAI/files/9010206/flash_FFC_3P.zip)

Hi @oto313 

Yes, sorry for delay, here are the files for flashing the EEPROM of the 3 versions, I could only test DM1090FFC version since the other two are not in production anymore, but it should work, let me know if you have any issues.
